version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  # Maintain dependencies for dockerfiles
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
        exclude-patterns:
          - "centos"
          - "almalinux"
    ignore:
      - dependency-name: "centos"
        update-types: ["version-update:semver-major"]
      - dependency-name: "almalinux"
        update-types: ["version-update:semver-major"]
