name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main when amzn2 version is updated
  push:
    branches:
      - main
    paths:
      - Dockerfile.amzn2023

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - run: git fetch --tags --force origin # WA: https://github.com/actions/checkout/issues/882
      - name: Test release condition
        id: release
        run: |
          RELEASE=false
          if make release/test 2> /dev/null; then RELEASE=true; fi
          echo "condition=${RELEASE}" >> "$GITHUB_OUTPUT"
          echo "version=$(make release/version)" >> "$GITHUB_OUTPUT"
      - name: Create release
        if: steps.release.outputs.condition == 'true'
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          name: ${{ steps.release.outputs.version }}
          tag_name:  ${{ steps.release.outputs.version }}
          generate_release_notes: true
          target_commitish: ${{ env.GITHUB_REF }}
          token: ${{ secrets.GH_RELEASES_TOKEN }}
