name: Run checks on pull request reviews
on: pull_request

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }}
        shell: bash
