name: Run checks on pull request reviews
on: pull_request

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }}
        shell: bash
